# Generated by Django 5.0.7 on 2024-08-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
