# Generated by Django 5.0.7 on 2024-08-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
